export const data = [
    { trainings: 'Hydrogennnnnnnnnnnnnnnnnnnnnnnnnn', department: 'H', frequently: 1.008, tags:"Basics" },
    { trainings: 'Helium', department: 'He', frequently: 4.0026, tags:"Tech-Support" },
    { trainings: 'Lithium', department: 'Li', frequently: 6.94, tags:"Basics" },
    { trainings: 'Beryllium', department: 'Be', frequently: 9.0122, tags:"Tech-Support" },
    { trainings: 'Boron', department: 'B', frequently: 10.81, tags:"Basics" },
    { trainings: 'Carbon', department: 'C', frequently: 12.011, tags:"Tech-Support" },
    { trainings: 'Nitrogen', department: 'N', frequently: 14.007, tags:"Basics" },
    { trainings: 'Oxygen', department: 'O', frequently: 15.999, tags:"Tech-Support" },
    { trainings: 'Fluorine', department: 'F', frequently: 18.998, tags:"Basics" },
    {  trainings: 'Neon', department: 'Ne', frequently: 20.180, tags:"Tech-Support" },
    {  trainings: 'Carbon', department: 'C', frequently: 12.011, tags:"Basics" },
    {  trainings: 'Nitrogen', department: 'N', frequently: 14.007, tags:"Basics" },
    {  trainings: 'Oxygen', department: 'O', frequently: 15.999, tags:"Tech-Support" },
    {  trainings: 'Fluorine', department: 'F', frequently: 18.998, tags:"Basics" },
    {  trainings: 'Neon', department: 'Ne', frequently: 20.180, tags:"Basics" },
    {  trainings: 'Carbon', department: 'C', frequently: 12.011, tags:"Basics" },
    {  trainings: 'Nitrogen', department: 'N', frequently: 14.007, tags:"Tech-Support" },
    {  trainings: 'Oxygen', department: 'O', frequently: 15.999, tags:"Basics" },
    {  trainings: 'Fluorine', department: 'F', frequently: 18.998, tags:"Tech-Support" },
    {  trainings: 'Neon', department: 'Ne', frequently: 20.180, tags:"Basics" }
]; 


export const data2 = [
    { 
        trainings: 'Hydrogen', 
        department: 'H', 
        frequently: 1.008, 
        tags: "Basics",
        email: 'hydrogen@example.com',
        action: 'Learn',
        location: 'Lab A',
        status: 'Active',
        job_title: 'Research Assistant'
    },
    { 
        trainings: 'Helium', 
        department: 'He', 
        frequently: 4.0026, 
        tags: "Tech-Support",
        email: 'helium@example.com',
        action: 'Teach',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Support Specialist'
    },
    { 
        trainings: 'Lithium', 
        department: 'Li', 
        frequently: 6.94, 
        tags: "Basics",
        email: 'lithium@example.com',
        action: 'Study',
        location: 'Lab C',
        status: 'Active',
        job_title: 'Lab Technician'
    },
    { 
        trainings: 'Beryllium', 
        department: 'Be', 
        frequently: 9.0122, 
        tags: "Tech-Support",
        email: 'beryllium@example.com',
        action: 'Train',
        location: 'Lab D',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Boron', 
        department: 'B', 
        frequently: 10.81, 
        tags: "Basics",
        email: 'boron@example.com',
        action: 'Develop',
        location: 'Lab A',
        status: 'Active',
        job_title: 'Developer'
    },
    { 
        trainings: 'Carbon', 
        department: 'C', 
        frequently: 12.011, 
        tags: "Tech-Support",
        email: 'carbon@example.com',
        action: 'Assist',
        location: 'Office B',
        status: 'Active',
        job_title: 'Support Engineer'
    },
    { 
        trainings: 'Nitrogen', 
        department: 'N', 
        frequently: 14.007, 
        tags: "Basics",
        email: 'nitrogen@example.com',
        action: 'Learn',
        location: 'Lab C',
        status: 'Inactive',
        job_title: 'Researcher'
    },
    { 
        trainings: 'Oxygen', 
        department: 'O', 
        frequently: 15.999, 
        tags: "Tech-Support",
        email: 'oxygen@example.com',
        action: 'Teach',
        location: 'Lab D',
        status: 'Active',
        job_title: 'Support Specialist'
    },
    { 
        trainings: 'Fluorine', 
        department: 'F', 
        frequently: 18.998, 
        tags: "Basics",
        email: 'fluorine@example.com',
        action: 'Study',
        location: 'Lab A',
        status: 'Active',
        job_title: 'Lab Technician'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
        { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
    { 
        trainings: 'Neon', 
        department: 'Ne', 
        frequently: 20.180, 
        tags: "Tech-Support",
        email: 'neon@example.com',
        action: 'Train',
        location: 'Office B',
        status: 'Inactive',
        job_title: 'Technical Trainer'
    },
];
